jetton_minter:
  data: fift/minter_data.fif
  func:
    - func/op-codes.func
    - func/params.func
    - func/helpers.func
    - func/jetton-utils.func
    - func/jetton-minter.func

jetton_wallet:
  data: fift/wallet_data.fif
  func:
    - func/op-codes.func
    - func/params.func
    - func/helpers.func
    - func/jetton-utils.func
    - func/jetton-wallet.func
