nft_collection:
  data: fift/collection-data.fif
  func:
    - func/helpers.func
    - func/params.func
    - func/op-codes.func
    - func/nft-collection.func
  tests:
    - tests/collection-tests.func
    - tests/collection-int.func

nft:
  data: fift/nft-data.fif
  func:
    - func/helpers.func
    - func/params.func
    - func/op-codes.func
    - func/nft-item.func
  tests:
    - tests/nft-tests.func
