nft_collection:
  data: fift/data.fif
  func:
    - func/helpers.func
    - func/params.func
    - func/op-codes.func
    - func/nft-collection.func

nft:
  func:
    - func/helpers.func
    - func/params.func
    - func/op-codes.func
    - func/nft-item.func
  tests:
    - tests/nft-tests.func
